In [ ]:
# Вправа 2 (1)

import numpy as np
import time

def task_2_numpy():
    n = int(input("n = "))
    start = time.time()
    arr = np.zeros((n, n), dtype=int)
    arr[::2, 1::2] = 1
    arr[1::2, ::2] = 1
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [32]:
task_2_numpy()

n =  5


[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
Час виконання NumPy: 3.409385681152344e-05


In [ ]:
# Вправа 2 (2)

def task_2_loop():
    n = int(input("n = "))
    start = time.time()
    arr = [[(i + j) % 2 for j in range(n)] for i in range(n)]
    end = time.time()
    for row in arr:
        print(row)
    print("Час виконання циклу:", end - start)

In [33]:
task_2_loop()

n =  5


[0, 1, 0, 1, 0]
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]
[1, 0, 1, 0, 1]
[0, 1, 0, 1, 0]
Час виконання циклу: 4.5299530029296875e-06


In [28]:
# Вправа 4 (1)

def task_4_numpy():
    n, m = map(int, input("n m = ").split())
    start = time.time()
    arr = np.zeros((n, m), dtype=int)
    arr[0] = np.arange(m)
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [29]:
task_4_numpy()

n m =  3 4


[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Час виконання NumPy: 2.0503997802734375e-05


In [30]:
# Вправа 4 (2)

def task_4_loop():
    n, m = map(int, input("n m = ").split())
    start = time.time()
    arr = [[0]*m for _ in range(n)]
    for j in range(m):
        arr[0][j] = j
    end = time.time()
    for row in arr:
        print(row)
    print("Час виконання циклу:", end - start)

In [31]:
task_4_loop()

n m =  3 4


[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
Час виконання циклу: 3.5762786865234375e-06


In [34]:
# Вправа 5 (1)

def task_5_numpy():
    n = int(input("n = "))
    start = time.time()
    arr = np.zeros((n, n), dtype=int)
    arr[::2] = 1
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [35]:
task_5_numpy()

n =  5


[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
Час виконання NumPy: 2.09808349609375e-05


In [36]:
# Вправа 5 (2)

def task_5_loop():
    n = int(input("n = "))
    start = time.time()
    arr = [[1 if i % 2 == 0 else 0 for j in range(n)] for i in range(n)]
    end = time.time()
    for row in arr:
        print(row)
    print("Час виконання циклу:", end - start)

In [37]:
task_5_loop()

n =  5


[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
Час виконання циклу: 5.4836273193359375e-06


In [ ]:
# Вправа 8 (1)

def task_8_numpy():
    arr = input("Введіть елементи через пробіл: ").split()
    start = time.time()
    arr = np.array(arr, dtype=float)
    zeros = np.sum(arr == 0)
    non_zeros = np.sum(arr != 0)
    end = time.time()
    print(f"Нулів: {zeros}")
    print(f"Не нулів: {non_zeros}")
    print("Час виконання NumPy:", end - start)

In [42]:
task_8_numpy()

Введіть елементи через пробіл:  3 4 0 9 8 2 4 0 8 4 0


Нулів: 3
Не нулів: 8
Час виконання NumPy: 6.103515625e-05


In [43]:
# Вправа 8 (2)

def task_8_loop():
    arr = input("Введіть елементи через пробіл: ").split()
    start = time.time()
    zeros = 0
    non_zeros = 0
    for x in arr:
        if float(x) == 0:
            zeros += 1
        else:
            non_zeros += 1
    end = time.time()
    print(f"Нулів: {zeros}")
    print(f"Не нулів: {non_zeros}")
    print("Час виконання циклу:", end - start)

In [44]:
task_8_loop()

Введіть елементи через пробіл:  3 4 0 9 8 2 4 0 8 4 0


Нулів: 3
Не нулів: 8
Час виконання циклу: 7.3909759521484375e-06


In [45]:
# Вправа 9 (1)

def task_9_numpy():
    n = int(input("n = "))
    start = time.time()
    arr = np.arange(n, -1, -1)
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [87]:
task_9_numpy()

n =  10


[10  9  8  7  6  5  4  3  2  1  0]
Час виконання NumPy: 1.239776611328125e-05


In [48]:
# Вправа 9 (2)

def task_9_loop():
    n = int(input("n = "))
    start = time.time()
    arr = [i for i in range(n, -1, -1)]
    end = time.time()
    print(arr)
    print("Час виконання циклу:", end - start)

In [86]:
task_9_loop()

n =  10


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Час виконання циклу: 1.430511474609375e-06


In [50]:
# Вправа 12 (1)

def task_12_numpy():
    n = int(input("n = "))
    start = time.time()
    arr = np.ones((n, n), dtype=float)
    arr[0, :] = 0
    arr[-1, :] = 0
    arr[:, 0] = 0
    arr[:, -1] = 0
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [54]:
task_12_numpy()

n =  4


[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
Час виконання NumPy: 3.147125244140625e-05


In [52]:
# Вправа 12 (2)

def task_12_loop():
    n = int(input("n = "))
    start = time.time()
    arr = [[1.0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if i == 0 or j == 0 or i == n-1 or j == n-1:
                arr[i][j] = 0.0
    end = time.time()
    for row in arr:
        print(row)
    print("Час виконання циклу:", end - start)

In [58]:
task_12_loop()

n =  4


[0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0]
Час виконання циклу: 4.0531158447265625e-06


In [69]:
# Вправа 13 (1)

def task_13_numpy():
    start = time.time()
    base = np.array([[0, 1], [1, 0]])
    arr = np.tile(base, (4, 4))
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [72]:
task_13_numpy()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Час виконання NumPy: 3.0994415283203125e-05


In [73]:
# Вправа 13 (2)

def task_13_loop():
    start = time.time()
    arr = [[(i + j) % 2 for j in range(8)] for i in range(8)]
    end = time.time()
    for row in arr:
        print(row)
    print("Час виконання циклу:", end - start)

In [74]:
task_13_loop()

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
Час виконання циклу: 5.7220458984375e-06


In [75]:
# Вправа 15 (1)

def task_15_numpy():
    n = int(input("n = "))
    start = time.time()
    arr = np.zeros((n, n), dtype=int)
    arr[:, 1::2] = 1
    end = time.time()
    print(arr)
    print("Час виконання NumPy:", end - start)

In [77]:
task_15_numpy()

n =  5


[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Час виконання NumPy: 3.075599670410156e-05


In [78]:
# Вправа 15 (2)

def task_15_loop():
    n = int(input("n = "))
    start = time.time()
    arr = []
    for i in range(n):
        row = []
        for j in range(n):
            if j % 2 == 1:
                row.append(1)
            else:
                row.append(0)
        arr.append(row)
    end = time.time()
    for row in arr:
        print(row)
    print("Час виконання циклу:", end - start)

In [79]:
task_15_loop()

n =  5


[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
Час виконання циклу: 6.4373016357421875e-06


In [80]:
# Вправа 19 (1)

def task_19_numpy():
    n = int(input("n = "))
    start = time.time()
    arr = np.linspace(0, 1, n+2)[1:-1]
    arr = np.round(arr, 3)
    end = time.time()
    print(arr)
    print("Час NumPy:", end - start)

In [81]:
task_19_numpy()

n =  10


[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]
Час NumPy: 0.0001983642578125


In [82]:
# Вправа 19 (2)

def task_19_loop():
    n = int(input("n = "))
    start = time.time()
    arr = []
    step = 1 / (n + 1)
    for i in range(1, n+1):
        arr.append(round(i * step, 3))
    end = time.time()
    print(arr)
    print("Час циклу:", end - start)

In [83]:
task_19_loop()

n =  10


[0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]
Час циклу: 2.2649765014648438e-05


$$
\begin{cases}
0\cdot x_1 + 1\cdot x_2 - 3\cdot x_3 + 4\cdot x_4 = -5\\[4pt]
1\cdot x_1 + 0\cdot x_2 - 2\cdot x_3 + 3\cdot x_4 = -4\\[4pt]
1\cdot x_1 + 1\cdot x_2 + 2\cdot x_3 - 5\cdot x_4 = 12\\[4pt]
4\cdot x_1 + 3\cdot x_2 - 5\cdot x_3 + 0\cdot x_4 = 5
\end{cases}
$$

<p style="text-align: center;">або, у матричному вигляді:</p>

$$
A=\begin{pmatrix}
0 & 1 & -3 & 4\\
1 & 0 & -2 & 3\\
1 & 1 & 2 & -5\\
4 & 3 & -5 & 0
\end{pmatrix},\qquad
\mathbf{b}=\begin{pmatrix}-5\\-4\\12\\5\end{pmatrix}.
$$

In [10]:
import numpy as np

A = np.array([[0, 1, -3, 4],
              [1, 0, -2, 3],
              [1, 1,  2, -5],
              [4, 3, -5, 0]], dtype=float)
b = np.array([-5, -4, 12, 5], dtype=float)

# Метод Крамера
detA = np.linalg.det(A)
if abs(detA) < 1e-12:
    raise ValueError("det(A) ~ 0, а отже метод Крамера непридатний.")
x_cramer = np.zeros(4)
for i in range(4):
    Ai = A.copy()
    Ai[:, i] = b
    x_cramer[i] = np.linalg.det(Ai) / detA
print("Розв’язок:", x_cramer)

# Перевірка a) A @ x
Ax = A @ x_cramer
print("A @ x_cramer =", Ax)
print("Співпадає з b:", np.allclose(Ax, b))

# Перевірка b) A^{-1} * b
x_inv = np.linalg.inv(A) @ b
print("\nA^{-1} * b =", x_inv)

# Перевірка c) numpy.linalg.solve()
x_solve = np.linalg.solve(A, b)
print("np.linalg.solve(A, b) =", x_solve)

# Порівняння
print("\nПорівняння результатів (allclose):")
print("Крамер vs A^{-1}b -", np.allclose(x_cramer, x_inv))
print("Крамер vs np.linalg.solve() -", np.allclose(x_cramer, x_solve))
print("A^{-1}b vs np.linalg.solve() -", np.allclose(x_inv, x_solve))

Розв’язок: [2. 4. 3. 0.]
A @ x_cramer = [-5. -4. 12.  5.]
Співпадає з b: True

A^{-1} * b = [2. 4. 3. 0.]
np.linalg.solve(A, b) = [2. 4. 3. 0.]

Порівняння результатів (allclose):
Крамер vs A^{-1}b - True
Крамер vs np.linalg.solve() - True
A^{-1}b vs np.linalg.solve() - True


$$
(A^2 - B^2)(A + B),
$$

<p style="text-align: center;">де</p>

$$
A = \begin{pmatrix}
7 & 2 & 0 \\
-7 & -2 & 1 \\
1 & 1 & 0
\end{pmatrix}, \qquad
B = \begin{pmatrix}
0 & 2 & 3 \\
1 & 0 & -2 \\
3 & 1 & 1
\end{pmatrix}.
$$

In [30]:
# NumPy

import numpy as np
import time

A = np.array([[7, 2, 0],
              [-7, -2, 1],
              [1, 1, 0]], dtype=float)
B = np.array([[0, 2, 3],
              [1, 0, -2],
              [3, 1, 1]], dtype=float)
start = time.time()
result_numpy = (A @ A - B @ B) @ (A + B)
end = time.time()
print("Результат (NumPy):")
print(result_numpy)
print("Час виконання NumPy:", end - start)

Результат (NumPy):
[[ 138.   88.   68.]
 [-154. -100.  -78.]
 [ -14.  -16.  -12.]]
Час виконання NumPy: 0.0001266002655029297


In [31]:
# Цикли

A_list = [[7, 2, 0],
          [-7, -2, 1],
          [1, 1, 0]]
B_list = [[0, 2, 3],
          [1, 0, -2],
          [3, 1, 1]]

def matmul(X, Y):
    return [[sum(X[i][k] * Y[k][j] for k in range(len(Y))) for j in range(len(Y[0]))] for i in range(len(X))]
    
def matadd(X, Y):
    return [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]

def matsub(X, Y):
    return [[X[i][j] - Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]

# (A^2 - B^2)(A + B)
start = time.time()
A2 = matmul(A_list, A_list)
B2 = matmul(B_list, B_list)
diff = matsub(A2, B2)
sumAB = matadd(A_list, B_list)
result_loop = matmul(diff, sumAB)
end = time.time()
print("Результат (цикли):")
for row in result_loop:
    print(row)
print("Час виконання циклів:", end - start)

Результат (цикли):
[138, 88, 68]
[-154, -100, -78]
[-14, -16, -12]
Час виконання циклів: 0.00015091896057128906
